# Generated by Django 5.0.1 on 2024-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, help_text='(optional)', verbose_name='Image URL'),
        ),
    ]
